require('v8-compile-cache')
window.fs = require('fs')
window.shell = require('electron').shell
window.globalagent = require('global-agent')
window.electronstore = require('electron-store')
window.log = require('electron-log')
window.qs = require('qs')
window.os = require('os')
window.uuidstring = require('uuid-by-string')
window.notifier = require('node-notifier')
window.nodescheduler = require('node-schedule')
window.path = require('path')
window.got = require('got')
window.feedparser = require('feedparser')
window.rssParser = require('rss-parser')
window.rssFinder = require('rss-finder')
window.electron = require('electron')
