export const addArticles = makeAction('ADD_ARTICLE')
export const getArticles = makeAction('SET_ARTICLE')
export const getTags = makeAction('SET_TAG')
export const addTag = makeAction('ADD_TAG')
export const updateTag = makeAction('UPDATE_TAG')
export const addFeed = makeAction('ADD_FEED')
export const getFeed = makeAction('SET_FEED')
export const removeFeed = makeAction('REMOVE_FEED')
export const removeArticle = makeAction('REMOVE_ARTICLE')
export const removeTag = makeAction('REMOVE_TAG')
export const markRead = makeAction('MARK_READ')
export const markUnread = makeAction('MARK_UNREAD')
export const favouriteArticle = makeAction('FAVOURITE_ARTICLE')
export const unFavouriteArticle = makeAction('UNFAVOURITE_ARTICLE')
export const incrementCount = makeAction('INCREMENT_FEEDCOUNT')
export const decrementCount = makeAction('DECREMENT_FEEDCOUNT')
export const setAppStatus = makeAction('APP_STATUS')
export const setBadgeCount = makeAction('SET_BADGE')

function makeAction (type) {
  return ({ dispatch }, ...args) => dispatch(type, ...args)
}
